name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.1
          terraform_wrapper: false
      
      - name: Build static-webapp
        run: zip -r static_webapp.zip static_webapp

      - name: Initialize Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: init 
          target: ./ami/static.pkr.hcl
      
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ./ami/static.pkr.hcl

      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          working_directory: ami
          target: ./static.pkr.hcl

      - name: Setup Go 
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        
      - name: Install Go dependencies
        working-directory: tests
        run: |
          go mod init tests 
          go mod tidy

      - name: Run Terratest tests
        working-directory: tests
        run: go test

      - name: Automatically create a Markdown docs for Terraform
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: infrastructure
          output-method: replace
          git-push: "true"